#!/bin/bash

MYSQL=`which mysql`
SQL_FILE=${SQL_FILE:="seed.sql"}

CMD="$MYSQL -u \"$MYSQL_DB_USER\" -p\"${MYSQL_DB_PASSWORD}\" $MYSQL_DB_NAME -h $MYSQL_HOST < $SQL_FILE"
echo "$CMD"

$MYSQL -u "$MYSQL_DB_USER" -p"${MYSQL_DB_PASSWORD}" $MYSQL_DB_NAME -h $MYSQL_HOST < $SQL_FILE
